
tasks:
  - name: Download and run MSSQL container
    init: |
      docker-compose up
  - name: Execute the container
    init: |
      docker exec -it localhost "bash"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart


vscode:
  extensions:
    - ms-mssql.mssql