tasks:
  - name: Copy requirements.txt content
    before:  |
      (
        cp requirements.txt src/web-api/app_requirements.txt
      )
  - name: Install python dependencies and run dev server
    init: |
      (
        set -e
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
      )
# optional: run backend immediately
# command: |
#   (
#     set -e
#     cd src/web-api/app/
#     uvicorn main:web_api --reload
#   )
  - name: docker-compose up
    init: |
      (    
        docker-compose up -d
        docker cp sample_data/seed.sql mssql:/
        docker cp sample_data/seed.sh mssql:/
        docker exec -it mssql "bash"
      )

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: web_api (Debugger)
    description: The dev server port 
    port: 8000
    onOpen: open-preview
  - name: web_api (Docker)
    description: The port of the docker container
    port: 80
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - ms-python.python
    - njpwerner.autodocstring
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
