
tasks:
  - name: Copy requirements.txt content
    before:  |
      (
        cp requirements.txt src/web-api/app_requirements.txt
      )
  - name: Install python dependencies and run dev server
    init: |
      (
        set -e
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
      )
    command: |
      (
        set -e
        cd src/web-api/app/
        uvicorn main:web_api --reload
      )
  - name: Download and run MSSQL container
    init: |
      (
        docker-compose up -d
        docker cp sample_data/seed.sql mssql:/
        docker cp sample_data/seed.sh mssql:/
        docker exec -it mssql "bash"
      )
  # - name: Execute the container
  #   init: |
  #     docker exec -it localhost "bash"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart


# vscode:
#   extensions:
#     - ms-mssql.mssql