version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Super@Admin123"
    ports:
      - "1433:1433"
    networks:
      - mssql
    hostname: "localhost"
networks:
  mssql:
    driver: bridge