version: '3.8'

services:
  web-api:
    build:
      context: ./src/web-api/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: web-api
    environment:
      DB_HOST: localhost
      DB_USER: sa
      DB_PASSWORD: Super@Admin123
      DB_NAME: onlineStoreDb
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Super@Admin123"
    ports:
      - "1433:1433"
    networks:
      - mssql
    hostname: "localhost"
networks:
  mssql:
    driver: bridge